all:	presas_x30.pdf presas_x29.pdf presas_x28.pdf presas_x27.pdf presas_x26.pdf presas_x25.pdf presas_x24.pdf presas_x23.pdf presas_x22.pdf presas_x21.pdf presas_x20.pdf presas_x19.pdf presas_x18.pdf presas_x17.pdf presas_x16.pdf presas_x15.pdf presas_x14.pdf presas_x13.pdf presas_x12.pdf presas_x11.pdf presas_x10.pdf presas_x9.pdf presas_x8.pdf presas_x7.pdf presas_x6.pdf presas_x5.pdf presas_x4.pdf presas_x3.pdf presas_x2.pdf presas_x1.pdf 

presas_x30.pdf:	presa30.dat
	python graph.py 30
presa30.dat:	runge_kutta.x
	./runge_kutta.x 30 20

presas_x29.pdf:	graph.py
	python graph.py 29
graph.py:	presa29.dat
presa29.dat:	runge_kutta.x
	./runge_kutta.c 29 20

presas_x28.pdf:	graph.py
	python graph.py 28
graph.py:	presa28.dat
presa28.dat:	runge_kutta.x
	./runge_kutta.c 28 20

presas_x27.pdf:	graph.py
	python graph.py 27
graph.py:	presa27.dat
presa27.dat:	runge_kutta.x
	./runge_kutta.x 27 20

presas_x26.pdf:	graph.py
	python graph.py 26
graph.py:	presa26.dat
presa26.dat:	runge_kutta.x
	./runge_kutta.x 26 20

presas_x25.pdf:	graph.py
	python graph.py 25
graph.py:	presa25.dat
presa25.dat:	runge_kutta.x
	./runge_kutta.x 25 20

presas_x24.pdf:	graph.py
	python graph.py 24
graph.py:	presa24.dat
presa24.dat:	runge_kutta.x
	./runge_kutta.x 24 20

presas_x23.pdf:	graph.py
	python graph.py 23
graph.py:	presa23.dat
presa23.dat:	runge_kutta.x
	./runge_kutta.x 23 20

presas_x22.pdf:	graph.py
	python graph.py 22
graph.py:	presa22.dat
presa22.dat:	runge_kutta.x
	./runge_kutta.x 22 20

presas_x21.pdf:	graph.py
	python graph.py 21
graph.py:	presa21.dat
presa21.dat:	runge_kutta.x
	./runge_kutta.x 21 20

presas_x20.pdf:	graph.py
	python graph.py 20
graph.py:	presa20.dat
presa20.dat:	runge_kutta.x
	./runge_kutta.x 20 20

presas_x19.pdf:	graph.py
	python graph.py 19
graph.py:	presa19.dat
presa19.dat:	runge_kutta.x
	./runge_kutta.x 19 20

presas_x18.pdf:	graph.py
	python graph.py 18
graph.py:	presa18.dat
presa18.dat:	runge_kutta.x.out
	./runge_kutta.x 18 20

presas_x17.pdf:	graph.py
	python graph.py 17
graph.py:	presa17.dat
presa17.dat:	runge_kutta.x
	./runge_kutta.x 17 20

presas_x16.pdf:	graph.py
	python graph.py 16
graph.py:	presa16.dat
presa16.dat:	runge_kutta.x
	./runge_kutta.x 16 20

presas_x15.pdf:	graph.py
	python graph.py 15
graph.py:	presa15.dat
presa15.dat:	runge_kutta.x
	./runge_kutta.x 15 20

presas_x14.pdf:	graph.py
	python graph.py 14
graph.py:	presa14.dat
presa14.dat:	runge_kutta.x
	./runge_kutta.x 14 20

presas_x13.pdf:	graph.py
	python graph.py 13
graph.py:	presa13.dat
presa13.dat:	runge_kutta.x
	./a.out 13 20

presas_x12.pdf:	graph.py
	python graph.py 12
graph.py:	presa12.dat
presa12.dat:	runge_kutta.x
	./runge_kutta.x 12 20

presas_x11.pdf:	graph.py
	python graph.py 11
graph.py:	presa11.dat
presa11.dat:	runge_kutta.x
	./runge_kutta.x 11 20

presas_x10.pdf:	graph.py
	python graph.py 10
graph.py:	presa10.dat
presa10.dat:	runge_kutta.x
	./runge_kutta.x 10 20

presas_x9.pdf:	graph.py
	python graph.py 9
graph.py:	presa9.dat
presa9.dat:	runge_kutta.x
	./runge_kutta.x 9 20

presas_x8.pdf:	graph.py
	python graph.py 8
graph.py:	presa8.dat
presa8.dat:	runge_kutta.x
	./runge_kutta.x 8 20

presas_x7.pdf:	graph.py
	python graph.py 7
graph.py:	presa7.dat
presa7.dat:	runge_kutta.x
	./runge_kutta.x 7 20

presas_x6.pdf:	graph.py
	python graph.py 6
graph.py:	presa6.dat
presa6.dat:	runge_kutta.x
	./runge_kutta.x 6 20

presas_x5.pdf:	graph.py
	python graph.py 5
graph.py:	presa5.dat
presa5.dat:	runge_kutta.x
	./runge_kutta.x 5 20

presas_x4.pdf:	graph.py
	python graph.py 4
graph.py:	presa4.dat
presa4.dat:	runge_kutta.x
	./runge_kutta.x 4 20

presas_x3.pdf:	graph.py
	python graph.py 3
graph.py:	presa3.dat
presa3.dat:	runge_kutta.x
	./runge_kutta.x 3 20

presas_x2.pdf:	graph.py
	python graph.py 2
graph.py:	presa2.dat
presa2.dat:	runge_kutta.x
	./runge_kutta.x 2 20

presas_x1.pdf:	graph.py
	python graph.py 1
graph.py:	presa1.dat
presa1.dat:	runge_kutta.x
	./runge_kutta.x 1 20


a.out: punto_1.c
	cc punto_1.c -lm -o runge_kutta.x 