all:	presas_x30.pdf presas_x29.pdf presas_x28.pdf presas_x27.pdf presas_x26.pdf presas_x25.pdf presas_x24.pdf presas_x23.pdf presas_x22.pdf presas_x21.pdf presas_x20.pdf presas_x19.pdf presas_x18.pdf presas_x17.pdf presas_x16.pdf presas_x15.pdf presas_x14.pdf presas_x13.pdf presas_x12.pdf presas_x11.pdf presas_x10.pdf presas_x9.pdf presas_x8.pdf presas_x7.pdf presas_x6.pdf presas_x5.pdf presas_x4.pdf presas_x3.pdf presas_x2.pdf presas_x1.pdf 

presas_x30.pdf:	graph.py
	python graph.py 30
graph.py:	presa30.dat
presa30.dat:	bla30.out
	./bla30.out 30 20
bla30.out:	punto_1.c
	cc punto_1.c -o bla30.out

presas_x29.pdf:	graph.py
	python graph.py 29
graph.py:	presa29.dat
presa29.dat:	bla29.out
	./bla29.out 29 20
bla29.out:	punto_1.c
	cc punto_1.c -o bla29.out

presas_x28.pdf:	graph.py
	python graph.py 28
graph.py:	presa28.dat
presa28.dat:	bla28.out
	./bla28.out 28 20
bla28.out:	punto_1.c
	cc punto_1.c -o bla28.out

presas_x27.pdf:	graph.py
	python graph.py 27
graph.py:	presa27.dat
presa27.dat:	bla27.out
	./bla27.out 27 20
bla27.out:	punto_1.c
	cc punto_1.c -o bla27.out

presas_x26.pdf:	graph.py
	python graph.py 26
graph.py:	presa26.dat
presa26.dat:	bla26.out
	./bla26.out 26 20
bla26.out:	punto_1.c
	cc punto_1.c -o bla26.out

presas_x25.pdf:	graph.py
	python graph.py 25
graph.py:	presa25.dat
presa25.dat:	bla25.out
	./bla25.out 25 20
bla25.out:	punto_1.c
	cc punto_1.c -o bla25.out

presas_x24.pdf:	graph.py
	python graph.py 24
graph.py:	presa24.dat
presa24.dat:	bla24.out
	./bla24.out 24 20
bla24.out:	punto_1.c
	cc punto_1.c -o bla24.out

presas_x23.pdf:	graph.py
	python graph.py 23
graph.py:	presa23.dat
presa23.dat:	bla23.out
	./bla23.out 23 20
bla23.out:	punto_1.c
	cc punto_1.c -o bla23.out

presas_x22.pdf:	graph.py
	python graph.py 22
graph.py:	presa22.dat
presa22.dat:	bla22.out
	./bla22.out 22 20
bla22.out:	punto_1.c
	cc punto_1.c -o bla22.out

presas_x21.pdf:	graph.py
	python graph.py 21
graph.py:	presa21.dat
presa21.dat:	bla21.out
	./bla21.out 21 20
bla21.out:	punto_1.c
	cc punto_1.c -o bla21.out

presas_x20.pdf:	graph.py
	python graph.py 20
graph.py:	presa20.dat
presa20.dat:	bla20.out
	./bla20.out 20 20
bla20.out:	punto_1.c
	cc punto_1.c -o bla20.out

presas_x19.pdf:	graph.py
	python graph.py 19
graph.py:	presa19.dat
presa19.dat:	bla19.out
	./bla19.out 19 20
bla19.out:	punto_1.c
	cc punto_1.c -o bla19.out

presas_x18.pdf:	graph.py
	python graph.py 18
graph.py:	presa18.dat
presa18.dat:	bla18.out
	./bla18.out 18 20
bla18.out:	punto_1.c
	cc punto_1.c -o bla18.out


presas_x17.pdf:	graph.py
	python graph.py 17
graph.py:	presa17.dat
presa17.dat:	bla17.out
	./bla17.out 17 20
bla17.out:	punto_1.c
	cc punto_1.c -o bla17.out

presas_x16.pdf:	graph.py
	python graph.py 16
graph.py:	presa16.dat
presa16.dat:	bla16.out
	./bla16.out 16 20
bla16.out:	punto_1.c
	cc punto_1.c -o bla16.out

presas_x15.pdf:	graph.py
	python graph.py 15
graph.py:	presa15.dat
presa15.dat:	bla15.out
	./bla15.out 15 20
bla15.out:	punto_1.c
	cc punto_1.c -o bla15.out

presas_x14.pdf:	graph.py
	python graph.py 14
graph.py:	presa14.dat
presa14.dat:	bla14.out
	./bla14.out 14 20
bla14.out:	punto_1.c
	cc punto_1.c -o bla14.out

presas_x13.pdf:	graph.py
	python graph.py 13
graph.py:	presa13.dat
presa13.dat:	bla13.out
	./bla13.out 13 20
bla13.out:	punto_1.c
	cc punto_1.c -o bla13.out

presas_x12.pdf:	graph.py
	python graph.py 12
graph.py:	presa12.dat
presa12.dat:	bla12.out
	./bla12.out 12 20
bla12.out:	punto_1.c
	cc punto_1.c -o bla12.out

presas_x11.pdf:	graph.py
	python graph.py 11
graph.py:	presa11.dat
presa11.dat:	bla11.out
	./bla11.out 11 20
bla11.out:	punto_1.c
	cc punto_1.c -o bla11.out

presas_x10.pdf:	graph.py
	python graph.py 10
graph.py:	presa10.dat
presa10.dat:	bla10.out
	./bla10.out 10 20
bla10.out:	punto_1.c
	cc punto_1.c -o bla10.out

presas_x9.pdf:	graph.py
	python graph.py 9
graph.py:	presa9.dat
presa9.dat:	bla9.out
	./bla9.out 9 20
bla9.out:	punto_1.c
	cc punto_1.c -o bla9.out

presas_x8.pdf:	graph.py
	python graph.py 8
graph.py:	presa8.dat
presa8.dat:	bla8.out
	./bla8.out 8 20
bla8.out:	punto_1.c
	cc punto_1.c -o bla8.out

presas_x7.pdf:	graph.py
	python graph.py 7
graph.py:	presa7.dat
presa7.dat:	bla7.out
	./bla7.out 7 20
bla7.out:	punto_1.c
	cc punto_1.c -o bla7.out

presas_x6.pdf:	graph.py
	python graph.py 6
graph.py:	presa6.dat
presa6.dat:	bla6.out
	./bla6.out 6 20
bla6.out:	punto_1.c
	cc punto_1.c -o bla6.out

presas_x5.pdf:	graph.py
	python graph.py 5
graph.py:	presa5.dat
presa5.dat:	bla5.out
	./bla5.out 5 20
bla5.out:	punto_1.c
	cc punto_1.c -o bla5.out

presas_x4.pdf:	graph.py
	python graph.py 4
graph.py:	presa4.dat
presa4.dat:	bla4.out
	./bla4.out 4 20
bla4.out:	punto_1.c
	cc punto_1.c -o bla4.out

presas_x3.pdf:	graph.py
	python graph.py 3
graph.py:	presa3.dat
presa3.dat:	bla3.out
	./bla3.out 3 20
bla3.out:	punto_1.c
	cc punto_1.c -o bla3.out

presas_x2.pdf:	graph.py
	python graph.py 2
graph.py:	presa2.dat
presa2.dat:	bla2.out
	./bla2.out 2 20
bla2.out:	punto_1.c
	cc punto_1.c -o bla2.out

presas_x1.pdf:	graph.py
	python graph.py 1
graph.py:	presa1.dat
presa1.dat:	bla1.out
	./bla1.out 1 20
bla1.out:	punto_1.c
	cc punto_1.c -o bla1.out
